version: '3.2'

services:
  badbank_front:
    build: './'
    depends_on:
      - badbank_back
    ports:
      - "3000:3000"
    networks:
      - badbank_network
#by labeling the hostname we can then use that in the URL in our DAL file rather than local host which avoids the issue where
#our middleware wasn't able to find the backend
  mongo:
    image: mongo
    hostname: badbank_mongo
    ports:
      - "27017:27017"
    networks:
      - badbank_network
    volumes:
      - ./app:/usr/src/app

#This is important when have multiple containers, lets them live and talk on the same network 
networks:
  badbank_network:
    name: badbank_network
    driver: bridge
